---
# Source: nfs-server-provisioner/templates/rolebinding.yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: nfs-server-provisioner
    chart: nfs-server-provisioner-0.3.1
    heritage: Tiller
    release: nfs-server
  name: nfs-server-nfs-server-provisioner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nfs-server-nfs-server-provisioner
subjects:
  - kind: ServiceAccount
    name: nfs-server-nfs-server-provisioner
    namespace: nfs
